version: "3.8"

services:
  app:
    image: mohamedelsayed7/todo-list-app:latest
    ports:
      - "80:4000"
    environment:
      - mongoDbUrl=mongodb+srv://test:01029054588@cluster0.obe5s.mongodb.net/todo?retryWrites=true&w=majority&appName=Cluster0
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 30s
      timeout: 5s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/.docker/config.json:/config.json:ro
    environment:
      - DOCKER_CONFIG=/
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://1397983422084812953/m_S_LmkCdhyypDaj1_wpNwgLZKSDg-cXxZwDiW2KBTOOIe-i0urNw-aPwPwJcS4DTzuJ
    command: --interval 30
