apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo
spec:
  selector:
    app: todo
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30080
