apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 80 #inside the cluster
      targetPort: 4000 #in app
      nodePort: 30080
